/**
 * This class is generated by jOOQ
 */
package com.biblioteca.generatedclasses;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bibliotecapo extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1197278376;

	/**
	 * The singleton instance of <code>bibliotecaPO</code>
	 */
	public static final Bibliotecapo BIBLIOTECAPO = new Bibliotecapo();

	/**
	 * No further instances allowed
	 */
	private Bibliotecapo() {
		super("bibliotecaPO");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.biblioteca.generatedclasses.tables.Autor.AUTOR,
			com.biblioteca.generatedclasses.tables.Emprestimo.EMPRESTIMO,
			com.biblioteca.generatedclasses.tables.Livro.LIVRO,
			com.biblioteca.generatedclasses.tables.LivroAutor.LIVRO_AUTOR,
			com.biblioteca.generatedclasses.tables.Multa.MULTA,
			com.biblioteca.generatedclasses.tables.Perfil.PERFIL,
			com.biblioteca.generatedclasses.tables.StatusEmprestimo.STATUS_EMPRESTIMO,
			com.biblioteca.generatedclasses.tables.Usuario.USUARIO);
	}
}
