/**
 * This class is generated by jOOQ
 */
package com.biblioteca.generatedclasses;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in bibliotecaPO
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table bibliotecaPO.Autor
	 */
	public static final com.biblioteca.generatedclasses.tables.Autor AUTOR = com.biblioteca.generatedclasses.tables.Autor.AUTOR;

	/**
	 * The table bibliotecaPO.Emprestimo
	 */
	public static final com.biblioteca.generatedclasses.tables.Emprestimo EMPRESTIMO = com.biblioteca.generatedclasses.tables.Emprestimo.EMPRESTIMO;

	/**
	 * The table bibliotecaPO.Livro
	 */
	public static final com.biblioteca.generatedclasses.tables.Livro LIVRO = com.biblioteca.generatedclasses.tables.Livro.LIVRO;

	/**
	 * The table bibliotecaPO.Livro_Autor
	 */
	public static final com.biblioteca.generatedclasses.tables.LivroAutor LIVRO_AUTOR = com.biblioteca.generatedclasses.tables.LivroAutor.LIVRO_AUTOR;

	/**
	 * The table bibliotecaPO.Multa
	 */
	public static final com.biblioteca.generatedclasses.tables.Multa MULTA = com.biblioteca.generatedclasses.tables.Multa.MULTA;

	/**
	 * The table bibliotecaPO.Perfil
	 */
	public static final com.biblioteca.generatedclasses.tables.Perfil PERFIL = com.biblioteca.generatedclasses.tables.Perfil.PERFIL;

	/**
	 * The table bibliotecaPO.Status_Emprestimo
	 */
	public static final com.biblioteca.generatedclasses.tables.StatusEmprestimo STATUS_EMPRESTIMO = com.biblioteca.generatedclasses.tables.StatusEmprestimo.STATUS_EMPRESTIMO;

	/**
	 * The table bibliotecaPO.Usuario
	 */
	public static final com.biblioteca.generatedclasses.tables.Usuario USUARIO = com.biblioteca.generatedclasses.tables.Usuario.USUARIO;
}
