/**
 * This class is generated by jOOQ
 */
package com.biblioteca.generatedclasses.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Emprestimo extends org.jooq.impl.TableImpl<com.biblioteca.generatedclasses.tables.records.EmprestimoRecord> {

	private static final long serialVersionUID = 1444659363;

	/**
	 * The singleton instance of <code>bibliotecaPO.Emprestimo</code>
	 */
	public static final com.biblioteca.generatedclasses.tables.Emprestimo EMPRESTIMO = new com.biblioteca.generatedclasses.tables.Emprestimo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.biblioteca.generatedclasses.tables.records.EmprestimoRecord> getRecordType() {
		return com.biblioteca.generatedclasses.tables.records.EmprestimoRecord.class;
	}

	/**
	 * The column <code>bibliotecaPO.Emprestimo.id</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.EmprestimoRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>bibliotecaPO.Emprestimo.data_inicio</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.EmprestimoRecord, java.sql.Date> DATA_INICIO = createField("data_inicio", org.jooq.impl.SQLDataType.DATE.nullable(false), this);

	/**
	 * The column <code>bibliotecaPO.Emprestimo.data_final</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.EmprestimoRecord, java.sql.Date> DATA_FINAL = createField("data_final", org.jooq.impl.SQLDataType.DATE.nullable(false), this);

	/**
	 * The column <code>bibliotecaPO.Emprestimo.fk_acesso_admin</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.EmprestimoRecord, java.lang.Integer> FK_ACESSO_ADMIN = createField("fk_acesso_admin", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>bibliotecaPO.Emprestimo.fk_acesso_usuario</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.EmprestimoRecord, java.lang.Integer> FK_ACESSO_USUARIO = createField("fk_acesso_usuario", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>bibliotecaPO.Emprestimo.fk_livro</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.EmprestimoRecord, java.lang.Integer> FK_LIVRO = createField("fk_livro", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>bibliotecaPO.Emprestimo.fk_status_emprestimo</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.EmprestimoRecord, java.lang.Integer> FK_STATUS_EMPRESTIMO = createField("fk_status_emprestimo", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>bibliotecaPO.Emprestimo</code> table reference
	 */
	public Emprestimo() {
		super("Emprestimo", com.biblioteca.generatedclasses.Bibliotecapo.BIBLIOTECAPO);
	}

	/**
	 * Create an aliased <code>bibliotecaPO.Emprestimo</code> table reference
	 */
	public Emprestimo(java.lang.String alias) {
		super(alias, com.biblioteca.generatedclasses.Bibliotecapo.BIBLIOTECAPO, com.biblioteca.generatedclasses.tables.Emprestimo.EMPRESTIMO);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.biblioteca.generatedclasses.tables.records.EmprestimoRecord, java.lang.Integer> getIdentity() {
		return com.biblioteca.generatedclasses.Keys.IDENTITY_EMPRESTIMO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.biblioteca.generatedclasses.tables.records.EmprestimoRecord> getPrimaryKey() {
		return com.biblioteca.generatedclasses.Keys.KEY_EMPRESTIMO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.biblioteca.generatedclasses.tables.records.EmprestimoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.biblioteca.generatedclasses.tables.records.EmprestimoRecord>>asList(com.biblioteca.generatedclasses.Keys.KEY_EMPRESTIMO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.biblioteca.generatedclasses.tables.records.EmprestimoRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.biblioteca.generatedclasses.tables.records.EmprestimoRecord, ?>>asList(com.biblioteca.generatedclasses.Keys.FK_EMPRESTIMO_1, com.biblioteca.generatedclasses.Keys.FK_EMPRESTIMO_2, com.biblioteca.generatedclasses.Keys.FK_EMPRESTIMO_3, com.biblioteca.generatedclasses.Keys.FK_EMPRESTIMO_4);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.biblioteca.generatedclasses.tables.Emprestimo as(java.lang.String alias) {
		return new com.biblioteca.generatedclasses.tables.Emprestimo(alias);
	}
}
