/**
 * This class is generated by jOOQ
 */
package com.biblioteca.generatedclasses.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Perfil extends org.jooq.impl.TableImpl<com.biblioteca.generatedclasses.tables.records.PerfilRecord> {

	private static final long serialVersionUID = 304092923;

	/**
	 * The singleton instance of <code>bibliotecaPO.Perfil</code>
	 */
	public static final com.biblioteca.generatedclasses.tables.Perfil PERFIL = new com.biblioteca.generatedclasses.tables.Perfil();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.biblioteca.generatedclasses.tables.records.PerfilRecord> getRecordType() {
		return com.biblioteca.generatedclasses.tables.records.PerfilRecord.class;
	}

	/**
	 * The column <code>bibliotecaPO.Perfil.id</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.PerfilRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>bibliotecaPO.Perfil.nome</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.PerfilRecord, java.lang.String> NOME = createField("nome", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this);

	/**
	 * Create a <code>bibliotecaPO.Perfil</code> table reference
	 */
	public Perfil() {
		super("Perfil", com.biblioteca.generatedclasses.Bibliotecapo.BIBLIOTECAPO);
	}

	/**
	 * Create an aliased <code>bibliotecaPO.Perfil</code> table reference
	 */
	public Perfil(java.lang.String alias) {
		super(alias, com.biblioteca.generatedclasses.Bibliotecapo.BIBLIOTECAPO, com.biblioteca.generatedclasses.tables.Perfil.PERFIL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.biblioteca.generatedclasses.tables.records.PerfilRecord, java.lang.Integer> getIdentity() {
		return com.biblioteca.generatedclasses.Keys.IDENTITY_PERFIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.biblioteca.generatedclasses.tables.records.PerfilRecord> getPrimaryKey() {
		return com.biblioteca.generatedclasses.Keys.KEY_PERFIL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.biblioteca.generatedclasses.tables.records.PerfilRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.biblioteca.generatedclasses.tables.records.PerfilRecord>>asList(com.biblioteca.generatedclasses.Keys.KEY_PERFIL_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.biblioteca.generatedclasses.tables.Perfil as(java.lang.String alias) {
		return new com.biblioteca.generatedclasses.tables.Perfil(alias);
	}
}
