/**
 * This class is generated by jOOQ
 */
package com.biblioteca.generatedclasses.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatusEmprestimo extends org.jooq.impl.TableImpl<com.biblioteca.generatedclasses.tables.records.StatusEmprestimoRecord> {

	private static final long serialVersionUID = 1437807758;

	/**
	 * The singleton instance of <code>bibliotecaPO.Status_Emprestimo</code>
	 */
	public static final com.biblioteca.generatedclasses.tables.StatusEmprestimo STATUS_EMPRESTIMO = new com.biblioteca.generatedclasses.tables.StatusEmprestimo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.biblioteca.generatedclasses.tables.records.StatusEmprestimoRecord> getRecordType() {
		return com.biblioteca.generatedclasses.tables.records.StatusEmprestimoRecord.class;
	}

	/**
	 * The column <code>bibliotecaPO.Status_Emprestimo.id</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.StatusEmprestimoRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>bibliotecaPO.Status_Emprestimo.nome</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.StatusEmprestimoRecord, java.lang.String> NOME = createField("nome", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this);

	/**
	 * Create a <code>bibliotecaPO.Status_Emprestimo</code> table reference
	 */
	public StatusEmprestimo() {
		super("Status_Emprestimo", com.biblioteca.generatedclasses.Bibliotecapo.BIBLIOTECAPO);
	}

	/**
	 * Create an aliased <code>bibliotecaPO.Status_Emprestimo</code> table reference
	 */
	public StatusEmprestimo(java.lang.String alias) {
		super(alias, com.biblioteca.generatedclasses.Bibliotecapo.BIBLIOTECAPO, com.biblioteca.generatedclasses.tables.StatusEmprestimo.STATUS_EMPRESTIMO);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.biblioteca.generatedclasses.tables.records.StatusEmprestimoRecord, java.lang.Integer> getIdentity() {
		return com.biblioteca.generatedclasses.Keys.IDENTITY_STATUS_EMPRESTIMO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.biblioteca.generatedclasses.tables.records.StatusEmprestimoRecord> getPrimaryKey() {
		return com.biblioteca.generatedclasses.Keys.KEY_STATUS_EMPRESTIMO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.biblioteca.generatedclasses.tables.records.StatusEmprestimoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.biblioteca.generatedclasses.tables.records.StatusEmprestimoRecord>>asList(com.biblioteca.generatedclasses.Keys.KEY_STATUS_EMPRESTIMO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.biblioteca.generatedclasses.tables.StatusEmprestimo as(java.lang.String alias) {
		return new com.biblioteca.generatedclasses.tables.StatusEmprestimo(alias);
	}
}
