/**
 * This class is generated by jOOQ
 */
package com.biblioteca.generatedclasses.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmprestimoRecord extends org.jooq.impl.UpdatableRecordImpl<com.biblioteca.generatedclasses.tables.records.EmprestimoRecord> implements org.jooq.Record7<java.lang.Integer, java.sql.Date, java.sql.Date, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 1795419344;

	/**
	 * Setter for <code>bibliotecaPO.Emprestimo.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Emprestimo.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>bibliotecaPO.Emprestimo.data_inicio</code>. 
	 */
	public void setDataInicio(java.sql.Date value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Emprestimo.data_inicio</code>. 
	 */
	public java.sql.Date getDataInicio() {
		return (java.sql.Date) getValue(1);
	}

	/**
	 * Setter for <code>bibliotecaPO.Emprestimo.data_final</code>. 
	 */
	public void setDataFinal(java.sql.Date value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Emprestimo.data_final</code>. 
	 */
	public java.sql.Date getDataFinal() {
		return (java.sql.Date) getValue(2);
	}

	/**
	 * Setter for <code>bibliotecaPO.Emprestimo.fk_acesso_admin</code>. 
	 */
	public void setFkAcessoAdmin(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Emprestimo.fk_acesso_admin</code>. 
	 */
	public java.lang.Integer getFkAcessoAdmin() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>bibliotecaPO.Emprestimo.fk_acesso_usuario</code>. 
	 */
	public void setFkAcessoUsuario(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Emprestimo.fk_acesso_usuario</code>. 
	 */
	public java.lang.Integer getFkAcessoUsuario() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>bibliotecaPO.Emprestimo.fk_livro</code>. 
	 */
	public void setFkLivro(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Emprestimo.fk_livro</code>. 
	 */
	public java.lang.Integer getFkLivro() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>bibliotecaPO.Emprestimo.fk_status_emprestimo</code>. 
	 */
	public void setFkStatusEmprestimo(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Emprestimo.fk_status_emprestimo</code>. 
	 */
	public java.lang.Integer getFkStatusEmprestimo() {
		return (java.lang.Integer) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.sql.Date, java.sql.Date, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.sql.Date, java.sql.Date, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.biblioteca.generatedclasses.tables.Emprestimo.EMPRESTIMO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field2() {
		return com.biblioteca.generatedclasses.tables.Emprestimo.EMPRESTIMO.DATA_INICIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field3() {
		return com.biblioteca.generatedclasses.tables.Emprestimo.EMPRESTIMO.DATA_FINAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.biblioteca.generatedclasses.tables.Emprestimo.EMPRESTIMO.FK_ACESSO_ADMIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.biblioteca.generatedclasses.tables.Emprestimo.EMPRESTIMO.FK_ACESSO_USUARIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.biblioteca.generatedclasses.tables.Emprestimo.EMPRESTIMO.FK_LIVRO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return com.biblioteca.generatedclasses.tables.Emprestimo.EMPRESTIMO.FK_STATUS_EMPRESTIMO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value2() {
		return getDataInicio();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value3() {
		return getDataFinal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getFkAcessoAdmin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getFkAcessoUsuario();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getFkLivro();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getFkStatusEmprestimo();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EmprestimoRecord
	 */
	public EmprestimoRecord() {
		super(com.biblioteca.generatedclasses.tables.Emprestimo.EMPRESTIMO);
	}

	/**
	 * Create a detached, initialised EmprestimoRecord
	 */
	public EmprestimoRecord(java.lang.Integer id, java.sql.Date dataInicio, java.sql.Date dataFinal, java.lang.Integer fkAcessoAdmin, java.lang.Integer fkAcessoUsuario, java.lang.Integer fkLivro, java.lang.Integer fkStatusEmprestimo) {
		super(com.biblioteca.generatedclasses.tables.Emprestimo.EMPRESTIMO);

		setValue(0, id);
		setValue(1, dataInicio);
		setValue(2, dataFinal);
		setValue(3, fkAcessoAdmin);
		setValue(4, fkAcessoUsuario);
		setValue(5, fkLivro);
		setValue(6, fkStatusEmprestimo);
	}
}
