/**
 * This class is generated by jOOQ
 */
package com.biblioteca.generatedclasses.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LivroAutorRecord extends org.jooq.impl.UpdatableRecordImpl<com.biblioteca.generatedclasses.tables.records.LivroAutorRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 1843271380;

	/**
	 * Setter for <code>bibliotecaPO.Livro_Autor.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Livro_Autor.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>bibliotecaPO.Livro_Autor.fk_livro</code>. 
	 */
	public void setFkLivro(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Livro_Autor.fk_livro</code>. 
	 */
	public java.lang.Integer getFkLivro() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>bibliotecaPO.Livro_Autor.fk_autor</code>. 
	 */
	public void setFkAutor(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Livro_Autor.fk_autor</code>. 
	 */
	public java.lang.Integer getFkAutor() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.biblioteca.generatedclasses.tables.LivroAutor.LIVRO_AUTOR.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.biblioteca.generatedclasses.tables.LivroAutor.LIVRO_AUTOR.FK_LIVRO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.biblioteca.generatedclasses.tables.LivroAutor.LIVRO_AUTOR.FK_AUTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getFkLivro();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getFkAutor();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LivroAutorRecord
	 */
	public LivroAutorRecord() {
		super(com.biblioteca.generatedclasses.tables.LivroAutor.LIVRO_AUTOR);
	}

	/**
	 * Create a detached, initialised LivroAutorRecord
	 */
	public LivroAutorRecord(java.lang.Integer id, java.lang.Integer fkLivro, java.lang.Integer fkAutor) {
		super(com.biblioteca.generatedclasses.tables.LivroAutor.LIVRO_AUTOR);

		setValue(0, id);
		setValue(1, fkLivro);
		setValue(2, fkAutor);
	}
}
