/**
 * This class is generated by jOOQ
 */
package com.biblioteca.generatedclasses.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LivroRecord extends org.jooq.impl.UpdatableRecordImpl<com.biblioteca.generatedclasses.tables.records.LivroRecord> implements org.jooq.Record11<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 1379863225;

	/**
	 * Setter for <code>bibliotecaPO.Livro.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Livro.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>bibliotecaPO.Livro.isbn</code>. 
	 */
	public void setIsbn(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Livro.isbn</code>. 
	 */
	public java.lang.String getIsbn() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>bibliotecaPO.Livro.capa</code>. 
	 */
	public void setCapa(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Livro.capa</code>. 
	 */
	public java.lang.String getCapa() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>bibliotecaPO.Livro.titulo</code>. 
	 */
	public void setTitulo(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Livro.titulo</code>. 
	 */
	public java.lang.String getTitulo() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>bibliotecaPO.Livro.autor</code>. 
	 */
	public void setAutor(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Livro.autor</code>. 
	 */
	public java.lang.String getAutor() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>bibliotecaPO.Livro.descricao</code>. 
	 */
	public void setDescricao(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Livro.descricao</code>. 
	 */
	public java.lang.String getDescricao() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>bibliotecaPO.Livro.ano_publicacao</code>. 
	 */
	public void setAnoPublicacao(java.sql.Date value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Livro.ano_publicacao</code>. 
	 */
	public java.sql.Date getAnoPublicacao() {
		return (java.sql.Date) getValue(6);
	}

	/**
	 * Setter for <code>bibliotecaPO.Livro.editora</code>. 
	 */
	public void setEditora(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Livro.editora</code>. 
	 */
	public java.lang.String getEditora() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>bibliotecaPO.Livro.genero</code>. 
	 */
	public void setGenero(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Livro.genero</code>. 
	 */
	public java.lang.String getGenero() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>bibliotecaPO.Livro.end_fisico</code>. 
	 */
	public void setEndFisico(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Livro.end_fisico</code>. 
	 */
	public java.lang.String getEndFisico() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>bibliotecaPO.Livro.fk_acesso</code>. 
	 */
	public void setFkAcesso(java.lang.Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Livro.fk_acesso</code>. 
	 */
	public java.lang.Integer getFkAcesso() {
		return (java.lang.Integer) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.biblioteca.generatedclasses.tables.Livro.LIVRO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.biblioteca.generatedclasses.tables.Livro.LIVRO.ISBN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.biblioteca.generatedclasses.tables.Livro.LIVRO.CAPA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.biblioteca.generatedclasses.tables.Livro.LIVRO.TITULO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.biblioteca.generatedclasses.tables.Livro.LIVRO.AUTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.biblioteca.generatedclasses.tables.Livro.LIVRO.DESCRICAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field7() {
		return com.biblioteca.generatedclasses.tables.Livro.LIVRO.ANO_PUBLICACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.biblioteca.generatedclasses.tables.Livro.LIVRO.EDITORA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.biblioteca.generatedclasses.tables.Livro.LIVRO.GENERO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.biblioteca.generatedclasses.tables.Livro.LIVRO.END_FISICO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field11() {
		return com.biblioteca.generatedclasses.tables.Livro.LIVRO.FK_ACESSO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getIsbn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getCapa();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getTitulo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getAutor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getDescricao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value7() {
		return getAnoPublicacao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getEditora();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getGenero();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getEndFisico();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value11() {
		return getFkAcesso();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LivroRecord
	 */
	public LivroRecord() {
		super(com.biblioteca.generatedclasses.tables.Livro.LIVRO);
	}

	/**
	 * Create a detached, initialised LivroRecord
	 */
	public LivroRecord(java.lang.Integer id, java.lang.String isbn, java.lang.String capa, java.lang.String titulo, java.lang.String autor, java.lang.String descricao, java.sql.Date anoPublicacao, java.lang.String editora, java.lang.String genero, java.lang.String endFisico, java.lang.Integer fkAcesso) {
		super(com.biblioteca.generatedclasses.tables.Livro.LIVRO);

		setValue(0, id);
		setValue(1, isbn);
		setValue(2, capa);
		setValue(3, titulo);
		setValue(4, autor);
		setValue(5, descricao);
		setValue(6, anoPublicacao);
		setValue(7, editora);
		setValue(8, genero);
		setValue(9, endFisico);
		setValue(10, fkAcesso);
	}
}
