/**
 * This class is generated by jOOQ
 */
package com.biblioteca.generatedclasses.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsuarioRecord extends org.jooq.impl.UpdatableRecordImpl<com.biblioteca.generatedclasses.tables.records.UsuarioRecord> implements org.jooq.Record8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Integer> {

	private static final long serialVersionUID = -1543433680;

	/**
	 * Setter for <code>bibliotecaPO.Usuario.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Usuario.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>bibliotecaPO.Usuario.usuario</code>. 
	 */
	public void setUsuario(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Usuario.usuario</code>. 
	 */
	public java.lang.String getUsuario() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>bibliotecaPO.Usuario.senha</code>. 
	 */
	public void setSenha(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Usuario.senha</code>. 
	 */
	public java.lang.String getSenha() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>bibliotecaPO.Usuario.email</code>. 
	 */
	public void setEmail(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Usuario.email</code>. 
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>bibliotecaPO.Usuario.telefone</code>. 
	 */
	public void setTelefone(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Usuario.telefone</code>. 
	 */
	public java.lang.String getTelefone() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>bibliotecaPO.Usuario.foto</code>. 
	 */
	public void setFoto(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Usuario.foto</code>. 
	 */
	public java.lang.String getFoto() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>bibliotecaPO.Usuario.status_usuario</code>. 
	 */
	public void setStatusUsuario(java.lang.Byte value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Usuario.status_usuario</code>. 
	 */
	public java.lang.Byte getStatusUsuario() {
		return (java.lang.Byte) getValue(6);
	}

	/**
	 * Setter for <code>bibliotecaPO.Usuario.fk_perfil</code>. 
	 */
	public void setFkPerfil(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>bibliotecaPO.Usuario.fk_perfil</code>. 
	 */
	public java.lang.Integer getFkPerfil() {
		return (java.lang.Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Integer> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.biblioteca.generatedclasses.tables.Usuario.USUARIO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.biblioteca.generatedclasses.tables.Usuario.USUARIO.USUARIO_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.biblioteca.generatedclasses.tables.Usuario.USUARIO.SENHA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.biblioteca.generatedclasses.tables.Usuario.USUARIO.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.biblioteca.generatedclasses.tables.Usuario.USUARIO.TELEFONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.biblioteca.generatedclasses.tables.Usuario.USUARIO.FOTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field7() {
		return com.biblioteca.generatedclasses.tables.Usuario.USUARIO.STATUS_USUARIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return com.biblioteca.generatedclasses.tables.Usuario.USUARIO.FK_PERFIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUsuario();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getSenha();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getTelefone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getFoto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value7() {
		return getStatusUsuario();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getFkPerfil();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsuarioRecord
	 */
	public UsuarioRecord() {
		super(com.biblioteca.generatedclasses.tables.Usuario.USUARIO);
	}

	/**
	 * Create a detached, initialised UsuarioRecord
	 */
	public UsuarioRecord(java.lang.Integer id, java.lang.String usuario, java.lang.String senha, java.lang.String email, java.lang.String telefone, java.lang.String foto, java.lang.Byte statusUsuario, java.lang.Integer fkPerfil) {
		super(com.biblioteca.generatedclasses.tables.Usuario.USUARIO);

		setValue(0, id);
		setValue(1, usuario);
		setValue(2, senha);
		setValue(3, email);
		setValue(4, telefone);
		setValue(5, foto);
		setValue(6, statusUsuario);
		setValue(7, fkPerfil);
	}
}
